name: PR Merged Workflow

on:
  pull_request:
    types:
      - closed

env:
    AWS_REGION: "us-east-1"
    tf_actions_working_dir: ./terraform
    CLUSTER_NAME: "test-cluster"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
            run:
              working-directory: ${{ env.tf_actions_working_dir }}
    permissions:
        id-token: write   
        contents: read
    steps:
      - name: Checkout/cloning the github repo
        uses: actions/checkout@v4


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::746196583728:role/test-role
          role-session-name: test-role
          aws-region: ${{ env.AWS_REGION }}

      - name: installing kubectl
        uses: marcofranssen/setup-kubectl@v0.3.0
        with:
          kubectl-version: 'latest'

      - name: terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform apply
        id: apply
        run: terraform apply -var="cluster_name:$CLUSTER_NAME" --auto-approve

      - name: connecting to the cluster
        run: |
            aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: installing argocd
        run: |
              kubectl create namespace argocd
              kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0/manifests/install.yaml

       